use fans;

INSERT INTO t_provinces (id, name) VALUES ('11', '北京');
INSERT INTO t_provinces (id, name) VALUES ('12', '天津');
INSERT INTO t_provinces (id, name) VALUES ('13', '河北');
INSERT INTO t_provinces (id, name) VALUES ('14', '山西');
INSERT INTO t_provinces (id, name) VALUES ('15', '内蒙古');
INSERT INTO t_provinces (id, name) VALUES ('21', '辽宁');
INSERT INTO t_provinces (id, name) VALUES ('22', '吉林');
INSERT INTO t_provinces (id, name) VALUES ('23', '黑龙江');
INSERT INTO t_provinces (id, name) VALUES ('31', '上海');
INSERT INTO t_provinces (id, name) VALUES ('32', '江苏');
INSERT INTO t_provinces (id, name) VALUES ('33', '浙江');
INSERT INTO t_provinces (id, name) VALUES ('34', '安徽');
INSERT INTO t_provinces (id, name) VALUES ('35', '福建');
INSERT INTO t_provinces (id, name) VALUES ('36', '江西');
INSERT INTO t_provinces (id, name) VALUES ('37', '山东');
INSERT INTO t_provinces (id, name) VALUES ('41', '河南');
INSERT INTO t_provinces (id, name) VALUES ('42', '湖北');
INSERT INTO t_provinces (id, name) VALUES ('43', '湖南');
INSERT INTO t_provinces (id, name) VALUES ('44', '广东');
INSERT INTO t_provinces (id, name) VALUES ('45', '广西');
INSERT INTO t_provinces (id, name) VALUES ('46', '海南');
INSERT INTO t_provinces (id, name) VALUES ('50', '重庆');
INSERT INTO t_provinces (id, name) VALUES ('51', '四川');
INSERT INTO t_provinces (id, name) VALUES ('52', '贵州');
INSERT INTO t_provinces (id, name) VALUES ('53', '云南');
INSERT INTO t_provinces (id, name) VALUES ('54', '西藏');
INSERT INTO t_provinces (id, name) VALUES ('61', '陕西');
INSERT INTO t_provinces (id, name) VALUES ('62', '甘肃');
INSERT INTO t_provinces (id, name) VALUES ('63', '青海');
INSERT INTO t_provinces (id, name) VALUES ('64', '宁夏');
INSERT INTO t_provinces (id, name) VALUES ('65', '新疆');
INSERT INTO t_provinces (id, name) VALUES ('71', '台湾');
INSERT INTO t_provinces (id, name) VALUES ('81', '香港');
INSERT INTO t_provinces (id, name) VALUES ('82', '澳门');
INSERT INTO t_provinces (id, name) VALUES ('100', '其他');
INSERT INTO t_provinces (id, name) VALUES ('400', '海外');


